spring:
  application:
    name: ProductManagementSystem

  spring:
    data:
      mongodb:
        host: localhost
        port: 27017
        database: product_data
        auto-index-creation: true